@URL = http://localhost:8000

###
GET {{URL}}/profiles

###
GET {{URL}}/users

###
POST  {{URL}}/seed

###
GET {{URL}}/bookreviews

###
GET {{URL}}/books

###
GET {{URL}}/authors

###
POST {{URL}}/books/11/reviews/1
